# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name': 'Performance SQL',
    'version': '1.0',
    'category': 'Hidden',
    'description': """
Module to test performance of query generated by expression.py
""",
    'data': [
        'security/ir.model.access.csv',
    ],
    'demo': [

    ],
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
